### ISSUE TITLE
No results for emacs-27/28/29?

### ISSUE THREAD

**Issue by thesamesam** [portagefilelist/client#26]
Hi!

I have emacs:27, emacs:28, emacs:29 installed and I definitely use pfl on a few of those systems to submit data, but:
```console
$ e-file emacs-27
SEARCH_FAILED
Invalid search criteria or nothing found. Either use a filename or complete path. Use * as a wildcard. Also check the path of the file. If the packagename is present the file is not recorded.
$  e-file emacs-28
SEARCH_FAILED
Invalid search criteria or nothing found. Either use a filename or complete path. Use * as a wildcard. Also check the path of the file. If the packagename is present the file is not recorded.
$ e-file emacs-29
SEARCH_FAILED
Invalid search criteria or nothing found. Either use a filename or complete path. Use * as a wildcard. Also check the path of the file. If the packagename is present the file is not recorded.
```

```console
$ equery f emacs | grep -i emacs-29$
/usr/bin/ctags-emacs-29
/usr/bin/ebrowse-emacs-29
/usr/bin/emacs-29
/usr/bin/emacsclient-emacs-29
/usr/bin/etags-emacs-29
/usr/include/emacs-29
/usr/share/info/emacs-29
```

**Comment by bananas-repos** [comment]
Thx sam for the ticket. Odd I did not get a notification. Will look into it.

**Comment by bananas-repos** [comment]
Well I do play around to limit the files which are recorded since there are millions of them and some are not worth the trouble.

I've updated the importer and maybe this will fix it: https://github.com/portagefilelist/server/commit/33d0c8a3e9ad8d8cb38639f3bb531af043fb4d01

The emacs package(s) are available: https://www.portagefilelist.de/index.php?p=packages&ps=emacs
but the file limitations could be the problem.

**Comment by bananas-repos** [comment]
@thesamesam Could you please reset your pfl timestamp by deleting `~/.pfl.info` and either run `pfl` manually or let the cron do it for you.
This way all your installed packages will be read again and uploaded. After that emacs-xx  should be found.

**Comment by thesamesam** [comment]
It works now, thank you very much!
