### ISSUE TITLE
Allow searching from package file list and increase pagination

### ISSUE THREAD

**Issue by leio** [portagefilelist/client#30]
Hello,

The old design used to have a search feature for package file contents and also allowed to increase the pagination size.
Now that doesn't seem possible, see e.g. https://www.portagefilelist.de/index.php?p=package&id=230dd2410917575e4a2c7fd73c03e8c8

It loads slower than smaller packages (signifying the backend maybe gets a performance hit despite the small pagination?), but then "only" shows 100 items per page (albeit I think that was the max on the old client, so that part might actually not be a regression at all), leading to 161 pages to click through to find something specific in this specific sample.
This makes it near-impossible to use for use cases like "Find the /usr/share/pkgconfig/*.pc files this package installs", or "See all the headers in /usr/include this package installs" (additionally complicated because the files are sorted by name, not full path now).

Thank you for your consideration and your work so far on modernizing the client!

**Comment by bananas-repos** [comment]
Hello and thank your for your feedback!

It is a mixed bag. There are packages which do have a "silly" large amount of files, I also exclude some of them already, which make the whole update and display process long to load.

Importing now uploads does slow down the webclient since there are indexes which do need updating. Waiting too long to do an import, the process would take much longer.

Splitting the data into more db tables will make the global search kind of impossible.

I've already added an issue and some ideas here: https://github.com/portagefilelist/server/issues/13 to improve this situation and will consider your idea, too.

Regards,
Banana

**Comment by bananas-repos** [comment]
I've update the website and you can now search within a package for its files:
https://www.portagefilelist.de/index.php?p=package&id=7504e13e28f0efce866660f4310f3a02

eg. https://www.portagefilelist.de/index.php?p=package&id=7504e13e28f0efce866660f4310f3a02&page=1&s=&sd=&ps=annotated*

Let me know what you think.

**Comment by leio** [comment]
That's a good improvements, albeit I would expect /usr/include/ to just show me all there without a `*`, but that's a matter of habit and getting used to it.
Another helpful thing would be to have the usual sortability on the columns, so could swap between sorting by Filename or full path ascending or descending. I would argue that full path sorting should be the default.

Thanks, at any rate I can use it again for my typical use case!

**Comment by bananas-repos** [comment]
> albeit I would expect /usr/include/ to just show me all there without 

Well the problem is performance, since the wildcard is a wildcard search which is always slower then an equal search.

> Another helpful thing would be to have the usual sortability on the columns, so could swap between sorting by Filename or full path ascending or descending. I would argue that full path sorting should be the default.

Added the sorting and also the result per page selection.
The default sort, well, the whole "story" is to search for a file, so the default sorting column is filename and not path.

Thank you again for your feedback, this helps a lot.

**Comment by bananas-repos** [comment]
Solution is live now for some time.
